[book]
title = "算法与数据结构学习指南"
authors = ["caoyang2002"]
description = "全面的算法与数据结构学习资料"
src = "src"
language = "zh-CN"


[build]
build-dir = "book"
create-missing = true

[output.html]
# 站点设置
site-url = "https://caoyang2002.github.io/AlgoNote/"
git-repository-url = "https://github.com/caoyang2002/AlgoNote"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/caoyang2002/AlgoNote/edit/main/src/{path}"

# 主题设置
default-theme = "navy"
preferred-dark-theme = "coal"
curly-quotes = true
mathjax-support = true
copy-fonts = true

# 目录折叠设置
fold.enable = true
fold.level = 3     # 默认折叠到第二级
# search.limit-results = 50  # 增加搜索结果数量
# title-expand-subsections = false  # 避免标题过长
# 代码块设置
# code.hidelines = "~"


# 搜索设置
search.enable = true
search.limit-results = 30
search.teaser-word-count = 30
search.use-boolean-and = true
search.boost-title = 2
search.boost-hierarchy = 1
search.boost-paragraph = 1
search.expand = true
search.heading-split-level = 3

# 页面标题设置
title-expand-subsections = true

# 额外的CSS和JS（如果有的话）
# additional-css = ["theme/custom.css"]
# additional-js = ["theme/custom.js"]

# 导航栏设置
[output.html.nav]
collapse = false
sticky = true

# 打印设置（修正：只使用一种格式）
[output.html.print]
enable = true
page-break = true

# 自定义头部HTML
[output.html.head]
custom = """
<meta property="og:type" content="website">
<meta property="og:title" content="算法与数据结构学习指南">
<meta property="og:description" content="全面的算法与数据结构学习资料">
<link rel="icon" href="favicon.png" type="image/png">
"""

# 代码块playground设置
[output.html.playground]
copyable = true
copy-js = true
line-numbers = false
editable = false

[preprocessor.cmdrun]
